language: cpp  
    
sudo: enabled
os: linux

compiler:
  - g++
  
addons:
  apt:
    packages:
    - g++-4.8
    - cmake

before_install:
  - sudo apt-get install libusb-1.0-0-dev
  - sudo apt-get install g++
  - sudo apt-get install cmake
  
script:
- makedir build
- cd build
- cmake..
- make

install: 
- ./build_libpixyusb.sh
- sudo./install_libpixyusb.sh
