language: cpp  
    
dist: trusty
sudo: false

os: linux

compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
    - cmake
    - libusb-1.0-0-dev
  
script:
- mkdir build
- cd build
- cmake ..
- make
