language: cpp  
    
sudo: enabled
os: linux

compiler:
  - g++
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - cmake

before_install:
  - sudo apt-get install g++
  - sudo apt-get install cmake

install: ./install_libpixyusb.sh
